// Command mkman renders the dnstree man page from the usage text the command
// itself prints, so the packages document the flags the binary actually has.
package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/rafaeljusto/dnstree/internal/cli"
)

func main() {
	version := flag.String("version", "dev", "the version in the page header")
	date := flag.String("date", "", "the date in the page header (default today, UTC)")
	output := flag.String("output", "", "write to this file instead of stdout")
	flag.Parse()

	when := *date
	if when == "" {
		when = time.Now().UTC().Format(time.DateOnly)
	}

	doc, err := parse(cli.Usage)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	page := render(doc, strings.TrimPrefix(*version, "v"), when)
	if *output == "" {
		fmt.Print(page)
		return
	}
	if err := os.WriteFile(*output, []byte(page), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// doc is the usage text taken apart: everything the man page is built from.
type doc struct {
	synopsis    string   // dnstree [flags] NAME [TYPE]
	description []string // one entry per paragraph
	options     []option
	exits       []exit
}

type option struct{ flags, text string }

type exit struct{ code, text string }

var (
	// An option line: the flags, then two or more spaces, then what it does.
	optionRE = regexp.MustCompile(`^\s+(\S.*?)\s{2,}(\S.*)$`)
	// One entry of the exit code sentence: the number and its meaning.
	exitRE = regexp.MustCompile(`^(\d+)\s+(\S.*)$`)
)

// parse reads the usage text. It is deliberately strict: the man page is only
// worth generating while it stays a faithful copy, so a shape this does not
// recognise is an error rather than a section quietly left out.
func parse(text string) (*doc, error) {
	paragraphs := paragraphs(text)
	if len(paragraphs) == 0 {
		return nil, fmt.Errorf("mkman: the usage text is empty")
	}

	head := paragraphs[0]
	if len(head) != 1 || !strings.HasPrefix(head[0], "usage: ") {
		return nil, fmt.Errorf("mkman: the usage text does not open with a one line synopsis")
	}

	d := doc{synopsis: strings.TrimPrefix(head[0], "usage: ")}
	for _, paragraph := range paragraphs[1:] {
		switch {
		case strings.HasPrefix(paragraph[0], " "):
			options, err := options(paragraph)
			if err != nil {
				return nil, err
			}
			d.options = append(d.options, options...)

		case strings.HasPrefix(paragraph[0], "Exit codes:"):
			exits, err := exits(paragraph)
			if err != nil {
				return nil, err
			}
			d.exits = append(d.exits, exits...)

		default:
			d.description = append(d.description, strings.Join(paragraph, "\n"))
		}
	}

	switch {
	case len(d.description) == 0:
		return nil, fmt.Errorf("mkman: the usage text says nothing about what the command does")
	case len(d.options) == 0:
		return nil, fmt.Errorf("mkman: the usage text lists no flags")
	case len(d.exits) == 0:
		return nil, fmt.Errorf("mkman: the usage text lists no exit codes")
	}
	return &d, nil
}

// paragraphs splits the text on blank lines, dropping them.
func paragraphs(text string) [][]string {
	var out [][]string
	var current []string
	for line := range strings.Lines(text) {
		line = strings.TrimRight(line, "\n")
		if strings.TrimSpace(line) == "" {
			if len(current) > 0 {
				out = append(out, current)
				current = nil
			}
			continue
		}
		current = append(current, line)
	}
	if len(current) > 0 {
		out = append(out, current)
	}
	return out
}

func options(lines []string) ([]option, error) {
	out := make([]option, 0, len(lines))
	for _, line := range lines {
		match := optionRE.FindStringSubmatch(line)
		if match == nil {
			return nil, fmt.Errorf("mkman: %q does not read as a flag and what it does", strings.TrimSpace(line))
		}
		out = append(out, option{flags: match[1], text: match[2]})
	}
	return out, nil
}

func exits(lines []string) ([]exit, error) {
	// The codes come either as one indented entry per line, or as a sentence
	// of comma separated entries that may wrap.
	entries := strings.Split(strings.TrimPrefix(strings.Join(lines, " "), "Exit codes:"), ",")
	if len(lines) > 1 && strings.HasPrefix(lines[1], " ") {
		entries = lines[1:]
	}

	var out []exit
	for _, entry := range entries {
		entry = strings.TrimSuffix(strings.TrimSpace(entry), ".")
		match := exitRE.FindStringSubmatch(entry)
		if match == nil {
			return nil, fmt.Errorf("mkman: %q does not read as an exit code and its meaning", entry)
		}
		out = append(out, exit{code: match[1], text: match[2]})
	}
	return out, nil
}

func render(d *doc, version, date string) string {
	var b strings.Builder

	fmt.Fprintf(&b, ".\\\" Generated by cmd/mkman from the usage text in internal/cli. Do not edit.\n")
	fmt.Fprintf(&b, ".TH DNSTREE 1 %q %q %q\n", date, "dnstree "+version, "User Commands")

	b.WriteString(".SH NAME\n")
	fmt.Fprintf(&b, "dnstree \\- %s\n", roff(cli.Summary))

	b.WriteString(".SH SYNOPSIS\n")
	b.WriteString(synopsis(d.synopsis) + "\n")

	b.WriteString(".SH DESCRIPTION\n")
	for i, paragraph := range d.description {
		if i > 0 {
			b.WriteString(".PP\n")
		}
		b.WriteString(roff(paragraph) + "\n")
	}

	b.WriteString(".SH OPTIONS\n")
	for _, opt := range d.options {
		b.WriteString(".TP\n")
		b.WriteString(flagSpec(opt.flags) + "\n")
		b.WriteString(roff(opt.text) + "\n")
	}

	b.WriteString(".SH EXIT STATUS\n")
	for _, e := range d.exits {
		b.WriteString(".TP\n")
		fmt.Fprintf(&b, "\\fB%s\\fR\n%s\n", e.code, roff(e.text))
	}

	// The examples are the one thing the usage text does not carry. They stay
	// short on purpose: the page is a reference, the README is the tour.
	b.WriteString(".SH EXAMPLES\n")
	for i, ex := range []struct{ what, command string }{
		{"Follow the delegation from the root down to a name:", "dnstree www.example.com A"},
		{"Ask every nameserver of every zone, and check the chain of trust:", "dnstree --all --dnssec example.com"},
		{"Draw the walk as it happens, then hand the finished tree to a document:", "dnstree --live --format ascii example.com MX"},
	} {
		if i > 0 {
			b.WriteString(".PP\n")
		}
		b.WriteString(roff(ex.what) + "\n.PP\n.RS 4\n.EX\n")
		b.WriteString(roff(ex.command) + "\n.EE\n.RE\n")
	}

	b.WriteString(".SH SEE ALSO\n")
	b.WriteString("\\fBdig\\fR(1), \\fBdelv\\fR(1), \\fBhost\\fR(1)\n")

	b.WriteString(".SH REPORTING BUGS\n")
	b.WriteString("https://github.com/rafaeljusto/dnstree/issues\n")

	return b.String()
}

// synopsis bolds the command and italicises everything it is given, keeping
// the brackets that say what is optional.
func synopsis(line string) string {
	fields := strings.Fields(line)
	if len(fields) == 0 {
		return ""
	}

	out := ".B " + roff(fields[0])
	if len(fields) == 1 {
		return out
	}

	args := make([]string, 0, len(fields)-1)
	for _, field := range fields[1:] {
		var left, right string
		if after, ok := strings.CutPrefix(field, "["); ok {
			left, field = "[", after
		}
		if before, ok := strings.CutSuffix(field, "]"); ok {
			right, field = "]", before
		}
		args = append(args, left+`\fI`+roff(field)+`\fR`+right)
	}
	return out + "\n" + strings.Join(args, " ")
}

// flagSpec bolds each flag and italicises the value it takes, so
// `--format FORMAT` reads the way every other page writes it.
func flagSpec(spec string) string {
	items := strings.Split(spec, ", ")
	for i, item := range items {
		words := strings.Fields(item)
		for j, word := range words {
			if strings.HasPrefix(word, "-") {
				words[j] = `\fB` + roff(word) + `\fR`
			} else {
				words[j] = `\fI` + roff(word) + `\fR`
			}
		}
		items[i] = strings.Join(words, " ")
	}
	return strings.Join(items, ", ")
}

var roffEscaper = strings.NewReplacer(`\`, `\e`, `-`, `\-`)

// roff escapes text for the formatter: a backslash starts an escape, a bare
// hyphen renders as a dash rather than the minus sign a flag needs, and a line
// opening with a control character would be read as a request.
func roff(text string) string {
	lines := strings.Split(roffEscaper.Replace(text), "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, ".") || strings.HasPrefix(line, "'") {
			lines[i] = `\&` + line
		}
	}
	return strings.Join(lines, "\n")
}
