#!/bin/sh
# Writes the Homebrew formula for a release, from the archives already in dist.
#
# The formula pours the same tarballs the release publishes rather than
# building from source, so what a Homebrew user runs is byte for byte what
# every other channel ships.
set -eu

version=${1:?usage: brew-formula.sh VERSION DIST}
dist=${2:?usage: brew-formula.sh VERSION DIST}

repo=https://github.com/rafaeljusto/dnstree
bare=${version#v}

sha() {
	archive="$dist/dnstree_${version}_$1.tar.gz"
	if [ ! -f "$archive" ]; then
		echo "brew-formula: $archive is missing; run the archives first" >&2
		exit 1
	fi
	# shasum is what macOS has, sha256sum what the runners have.
	if command -v shasum >/dev/null 2>&1; then
		shasum -a 256 "$archive" | cut -d' ' -f1
	else
		sha256sum "$archive" | cut -d' ' -f1
	fi
}

# on_arm and on_intel read the machine Homebrew is installing on, so one
# formula covers both architectures of both systems.
block() {
	cat <<-BLOCK
			    on_$2 do
			      url "$repo/releases/download/$version/dnstree_${version}_$1_$3.tar.gz"
			      sha256 "$(sha "$1_$3")"
			    end
	BLOCK
}

cat <<FORMULA
# Generated by scripts/brew-formula.sh for $version. Do not edit.
class Dnstree < Formula
  desc "Resolve a name from the root servers down, and draw the path it took"
  homepage "$repo"
  version "$bare"
  license "MIT"

  on_macos do
$(block darwin arm arm64)
$(block darwin intel amd64)
  end

  on_linux do
$(block linux arm arm64)
$(block linux intel amd64)
  end

  def install
    bin.install "dnstree"
    man1.install "dnstree.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dnstree --version")
  end
end
FORMULA
